### ISSUE TITLE
Messages sent are shown weirdly in the log

### ISSUE THREAD

**Issue by itslukej** [ezzybot/ezzybot#37]
```
[05/01/2016][17:26:47][SEND] b'PRIVMSG #irc :[iovoid] help list quit flush reload\r\n'
```
Only a problem with python3

**Comment by ThePhoenix47** [comment]
The reason this error occurs is that python 3 uses unicode as the default string type, while python 2 uses bytes. As the message sent is a bytes string, python 3 outputs it this way. Because python 3 has completely changed the handling of strings, it seems that it is quite difficult to find a solution that is compatible with both python 2 and 3.

**Comment by IndigoTiger** [comment]
This is a similar situation to `raw_input()` and `input()`, so I'd imagine handling it the same way will work

**Comment by BWBellairs** [comment]
I've fixed this. The bot doesn't quit on unicode errors now. stuff like u' does not appear in log anymore but does appear in terminal. Fix pending
